services:
  - type: web
    name: vtb-faceguard
    runtime: docker
    repo: https://github.com/kkochetkov05/vtb-faceguard
    branch: main
    plan: starter
    region: frankfurt
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: UPLOAD_DIR
        value: /var/data/uploads
      - key: DB_PATH
        value: /var/data/db.json
